### ISSUE TITLE
has-error not getting set

### ISSUE THREAD

**Issue by haldiggs** [formvalidation/formvalidation.io#1]
I'm not sure if this is just something I am missing in setting up the form. I have a simple form that is being validated. I do see the messages under the fields. I was not seeing any red colors as I see in the examples. Investigation revealed that the has-error class is not being set. If I do it manually in the dev toolbar I see what I'm looking for.

Can you give me some idea as to what to look for?

btw I love the toolset. Just started looking at it.

**Comment by nghuuphuoc** [comment]
Can you give me your form's code?, or better, create a [jsfiddle](http://jsfiddle.net/) for it?

By the way, the main repository for the project is https://github.com/formvalidation/formvalidation

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by haldiggs** [comment]
ok... I finally figured it out. although I was using a form, my controls were not inside another div with a class=form-group. Is that in the documentation somewhere? I guess I was not adhering to proper bootstrap forms.

**Comment by nghuuphuoc** [comment]
Take a look at [row.selector](http://formvalidation.io/settings/#form-row-selector) option.

v0.6.0:
```javascript
$(document).ready(function() {
    $('#groupForm').formValidation({
        framework: 'bootstrap',
        row: {
            selector: 'td'
        },
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            ...
        }
    });
});
```

v0.5.3:
```javascript
$(document).ready(function() {
    $('#groupForm').bootstrapValidator({
        group: 'td',
        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            ...
        }
    });
});
```

**Comment by nghuuphuoc** [comment]
This issue was moved to formvalidation/support#1
