### ISSUE TITLE
Dynamic forms : enabling

### ISSUE THREAD

**Issue by haldiggs** [formvalidation/formvalidation.io#10]
Sorry, this isn't really an issue but more of a question. I didn't see anywhere else to ask. I have a form that I am loading dynamically (partial). I tried `$(form).data('formValidation').resetForm();` but nothing seems to make the controls respect the validation.

The validation code lives in a separate js file so its obvious it won't get initialized upon the first screen load. It might just be the selectors. I'm using bootstrap and the controls are in this format:

	<div class="row">
		<div class="col-md-12">
			<input type="text" name="idTest" id="idTest" />
		</div>
	</div>
is it simply that its not in perfect bootstrap form? with a form-group class?

**Comment by nghuuphuoc** [comment]
This issue was moved to formvalidation/support#23
