### ISSUE TITLE
Handle credit card validation for Elo, Hiper and Hipercard

### ISSUE THREAD

**Issue by shaunwarman** [formvalidation/formvalidation.io#3]

**Comment by nghuuphuoc** [comment]
I couldn't find much information about these cards.
Is [this](https://gist.github.com/danielfilho/9cd8fb61a39778be587c) correct?
Can you give me the official/correct formats of these cards?

**Comment by nghuuphuoc** [comment]
This issue was moved to formvalidation/support#2
