### ISSUE TITLE
Migration from v.0.5.2 to v.0.6.0 not working

### ISSUE THREAD

**Issue by bhames50** [formvalidation/formvalidation.io#5]
I purchased the Developer's license for v.0.6.0 today, and downloaded the .zip file. I unzipped the .js and the .css files, and installed them into my resources directory. I then updated my links to point to formValidation.css and formValidation.js.

I then updated the call to initiate the validator from:
		    $('#advanced-search-form').boostrapValidator({
		        fields: {
		            equipId: {
		                validators: {
		                    regexp: {
		                        regexp: /^[-A-Za-z0-9]{1,16}$/,
		                        message: 'Invalid format'
		                    }, ...
to
		    $('#advanced-search-form').formValidation({
		        fields: {
		            equipId: {
		                validators: {
		                    regexp: {
		                        regexp: /^[-A-Za-z0-9]{1,16}$/,
		                        message: 'Invalid format'
		                    }, ...

and when I run the application, none of the validation is working, and I get the following JavaScript error when I debug the JSP:

SCRIPT445: Object doesn't support this action 
formValidation.js, line 2106 character 25

I've been over the website looking for steps I might have missed, but I can't find any.

I noticed the migration steps on the website were from v.0.5.3 to v.0.6.0, but I wouldn't have thought that there would be that much difference between v.0.5.2 and v.0.5.3.

The code is currently working, and I was merely trying to upgrade to the latest version.

Any help you can give would be appreciated.

**Comment by nghuuphuoc** [comment]
@bhames50 
Your upgrading seems good. You also don't need to do anything when upgrading from v0.5.2 to v0.5.3.
In this case, can you please give me your HTML form and the Javascript validation call for it?
I will try to find out the reason.

**Comment by bhames50** [comment]
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Test Page</title>

	<link href="${pageContext.request.contextPath}/resources/css/bootstrap.css" rel="stylesheet">
    <link href="${pageContext.request.contextPath}/resources/css/formValidation.css" rel="stylesheet"> 	
	
    <script type="text/javascript" src="${pageContext.request.contextPath}/resources/js/jquery-2.1.1.js"></script>
    <script type="text/javascript" src="${pageContext.request.contextPath}/resources/js/bootstrap.js"></script> 
    <script type="text/javascript" src="${pageContext.request.contextPath}/resources/js/formValidation.js"></script>    
    
    <script type="text/javascript">
    	window.contextPath = "${pageContext.request.contextPath}";
    </script>
    
<script type="text/javascript">

        $(function(){  
		    $('#advanced-search-form').formValidation({
		        fields: {
		            equipId: {
		                validators: {
		                    regexp: {
		                        regexp: mil.navy.spawar.regexes.equipId,
		                        message: 'Invalid format'
		                    },
				            callback: {
				                message: 'Please fill at least one of these fields',
				                callback: function(value, validator) {
				                    return checkGroupEmpty(value, validator);
				                }
				            }			    
		                }	                
		            },
		            code: {
		                validators: {
		                    regexp: {
		                        regexp: mil.navy.spawar.regexes.code,
		                        message: 'Invalid format'
		                    },
		                    callback: {
		                        message: 'Please fill at least one of these fields',
		                        callback: function(value, validator) {
		                            return checkGroupEmpty(value, validator);
		                        }
		                    }			            
		                }
		            },
		            lName: {
		                validators: {
		                    regexp: {
		                        regexp: mil.navy.spawar.regexes.name,
		                        message: 'Invalid format'
		                    },
		                    callback: {
		                        message: 'Please fill at least one of these fields',
		                        callback: function(value, validator) {
		                            return checkGroupEmpty(value, validator);
		                        }
		                    }			            
		                }
		            },
		            fName: {
		                validators: {
		                    regexp: {
		                        regexp: mil.navy.spawar.regexes.name,
		                        message: 'Invalid format'
		                    },
		                    callback: {
		                        message: 'Please fill at least one of these fields',
		                        callback: function(value, validator) {
		                            return checkGroupEmpty(value, validator);
		                        }
		                    }		            
		                }	
		            },
		            mi: {
		                validators: {
		                    regexp: {
		                        regexp: mil.navy.spawar.regexes.middleInitial,
		                        message: 'Invalid format'
		                    },
		                    callback: {
		                        message: 'Please fill at least one of these fields',
		                        callback: function(value, validator) {
		                            return checkGroupEmpty(value, validator);
		                        }
		                    }
		                }
		            },
		            emp_cat: {
		                validators: {
		                    regexp: {
		                        regexp: mil.navy.spawar.regexes.employeeCategory,
		                        message: 'Invalid format'
		                    },
		                    callback: {
		                        message: 'Please fill at least one of these fields',
		                        callback: function(value, validator) {
		                            return checkGroupEmpty(value, validator);
		                        }
		                    }
		                }
		            },
		            seat_type: {
		                validators: {
		                    regexp: {
		                        regexp: mil.navy.spawar.regexes.seatType,
		                        message: 'Invalid format'
		                    },
		                    callback: {
		                        message: 'Please fill at least one of these fields',
		                        callback: function(value, validator) {
		                            return checkGroupEmpty(value, validator);
		                        }
		                    }
		                }
		            },		            
		            nwae: {
		                validators: {
		                    regexp: {
		                        regexp: mil.navy.spawar.regexes.nwae,
		                        message: mil.navy.spawar.validationMessages.nwae
		                    },
		                    callback: {
		                        message: 'Please fill at least one of these fields',
		                        callback: function(value, validator) {
		                            return checkGroupEmpty(value, validator);
		                        }
		                    }		                    
		                }
		            },
		            network: {
		                validators: {
		                    regexp: {
		                        regexp: mil.navy.spawar.regexes.network,
		                        message: 'Invalid format'
		                    },
		                    callback: {
		                        message: 'Please fill at least one of these fields',
		                        callback: function(value, validator) {
		                            return checkGroupEmpty(value, validator);
		                        }
		                    }		                    
		                }
		            }		            
		        }
		    });
		    
		    function checkGroupEmpty(value, validator) {
		        var $groups = $('#advanced-search-form').find('.required-group'),
		            total   = $groups.length;
		        
		        // If all elements are empty, then return false
		        if ($groups.filter(function() {
		                return $(this).val() === '';
		            }).length === total)
		        {
		            return false;
		        } else {
		            // Update the status of this validator to all fields
		            $groups.each(function() {
		                validator.updateStatus($(this).attr('name'), validator.STATUS_VALID, 'callback');
		            });

		            // Otherwise, returns true
		            return true;
		        }
		    };
	    });
        
    </script>		    
</head>
<body>
<div class="container-fluid">
	<h2 class="text-primary col-md-offset-2 col-sm-offset-2">Test Page</h2>
	<div class="row" id="advanced-search">
		<form id="advanced-search-form" class="form-horizontal">
			<div class="form-group">
				<div class="col-md-2 col-sm-2 text-right text-primary">
					<label for="equipId" class="control-label">User ID</label>
				</div>
				<div class="col-md-3 col-sm-3">
					<input type="text" id="equipId" name="equipId"
						class="form-control input-sm required-group" placeholder=" "/>
				</div>
				<div class="col-md-2 col-sm-2 text-right text-primary">
					<span>&nbsp;</span>
				</div>
				<div class="col-md-3 col-sm-3">
					<span>&nbsp;</span>
				</div>
				<div class="col-md-2 col-sm-2 text-left text-primary">
					<span>&nbsp;</span>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-2 col-sm-2 text-right text-primary">
					<label for="code" class="control-label">Code</label>
				</div>
				<div class="col-md-3 col-sm-3">
					<input type="text" id="code" name="code"
						class="form-control input-sm required-group" placeholder=" "/>
				</div>
				<div class="col-md-2 col-sm-2 text-left text-primary">
					<span>&nbsp;</span>
				</div>
				<div class="col-md-3 col-sm-3">
					<span>&nbsp;</span>
				</div>
				<div class="col-md-2 col-sm-2 text-left text-primary">
					<span>&nbsp;</span>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-2 col-sm-2 text-right text-primary">
					<label for="lName" class="control-label">Last Name</label>
				</div>
				<div class="col-md-3 col-sm-3">
					<input type="text" id="lName" name="lName"
						class="form-control input-sm required-group" placeholder=" "/>
				</div>
				<div class="col-md-2 col-sm-2 text-right text-primary">
					<span>&nbsp;</span>
				</div>
				<div class="col-md-3 col-sm-3">
					<span>&nbsp;</span>
				</div>
				<div class="col-md-2 col-sm-2 text-left text-primary">
					<span>&nbsp;</span>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-2 col-sm-2 text-right text-primary">
					<label for="fName" class="control-label">First Name</label>
				</div>
				<div class="col-md-3 col-sm-3">
					<input type="text" id="fName" name="fName"
						class="form-control input-sm required-group" placeholder=" "/>
				</div>
				<div class="col-md-2 col-sm-2 text-right text-primary">
					<span>&nbsp;</span>
				</div>
				<div class="col-md-3 col-sm-3">
					<span>&nbsp;</span>
				</div>
				<div class="col-md-2 col-sm-2 text-left text-primary">
					<span>&nbsp;</span>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-2 col-sm-2 text-right text-primary">
					<label for="mi" class="control-label">Middle Initial</label>
				</div>
				<div class="col-md-3 col-sm-3">
					<input type="text" id="mi" name="mi"
						class="form-control input-sm required-group" placeholder=" "/>
				</div>
				<div class="col-md-2 col-sm-2 text-right text-primary">
					<span>&nbsp;</span>
				</div>
				<div class="col-md-3 col-sm-3">
					<span>&nbsp;</span>
				</div>
				<div class="col-md-2 col-sm-2 text-left text-primary">
					<span>&nbsp;</span>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-2 col-sm-2 text-right text-primary">
					<label for="emp_cat" class="control-label">Employee
						Category</label>
				</div>
				<div class="col-md-3 col-sm-3">
					<select id="emp_cat" name="emp_cat"
						class="form-control input-sm required-group">
						<option value="">Any</option>
						<option value="CIV">Civilian</option>
						<option value="GOV">Government</option>
						<option value="CTR">Contractor</option>
					</select>
				</div>
				<div class="col-md-2 col-sm-2 text-right text-primary">
					<span>&nbsp;</span>
				</div>
				<div class="col-md-3 col-sm-3">
					<span>&nbsp;</span>
				</div>
				<div class="col-md-2 col-sm-2 text-left text-primary">
					<span>&nbsp;</span>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-2 col-sm-2 text-right text-primary">
					<label for="seat_type" class="control-label">Seat Type</label>
				</div>
				<div class="col-md-3 col-sm-3">
					<select id="seat_type" name="seat_type"
						class="form-control input-sm required-group">
						<option value="">Any</option>
						<option value="D">Direct</option>
						<option value="P">Production Overhead</option>
						<option value="S">Service Center</option>
						<option value="G">G&amp;A Overhead</option>
					</select>
				</div>
				<div class="col-md-2 col-sm-2 text-right text-primary">
					<span>&nbsp;</span>
				</div>
				<div class="col-md-3 col-sm-3">
					<span>&nbsp;</span>
				</div>
				<div class="col-md-2 col-sm-2 text-left text-primary">
					<span>&nbsp;</span>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-2 col-sm-2 text-right text-primary">
					<label for="nwae" class="control-label">NWAE</label>
				</div>
				<div class="col-md-3 col-sm-3">
					<input type="text" id="nwae" name="nwae"
						class="form-control input-sm required-group" placeholder="123456123456.XXXX.XXXX"/>
				</div>
				<div class="col-md-2 col-sm-2 text-right text-primary">
					<span>&nbsp;</span>
				</div>
				<div class="col-md-3 col-sm-3">
					<span>&nbsp;</span>
				</div>
				<div class="col-md-2 col-sm-2 text-left text-primary">
					<span>&nbsp;</span>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-2 col-sm-2 text-right text-primary">
					<label for="network" class="control-label">Funding Type</label>
				</div>
				<div class="col-md-3 col-sm-3">
					<select id="network" name="network"
						class="form-control input-sm required-group">
						<option value="">Any</option>
						<option value="1">Direct</option>
						<option value="3">Overhead</option>
						<option value="4">Service Center</option>
					</select>
				</div>
				<div class="col-md-2 col-sm-2 text-right text-primary">
					<span>&nbsp;</span>
				</div>
				<div class="col-md-3 col-sm-3">
					<span>&nbsp;</span>
				</div>
				<div class="col-md-2 col-sm-2 text-left text-primary">
					<span>&nbsp;</span>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-10 col-sm-offset-2">
					<button type="submit" id="advanced-search-action" disabled="disabled"
						class="btn btn-primary">Search</button>
				</div>
			</div>
		</form>
	</div>
</body>
</html>

**Comment by bhames50** [comment]
I cut down one of my JSP pages to the bare minimum so that you could see all the code, and it is doing the same thing. You should be able to recreate it with this code.

Thanks for your help, and let me know if there is anything else you need!

**Comment by bhames50** [comment]
Since bootstrap doesn't include the version number in their files, I thought you should know I'm using v3.2.0.

**Comment by nghuuphuoc** [comment]
I know the reason causing the issue.
The problem is that you don't include the ```bootstrap.js``` which is provided by plugin.
It is NOT bootstrap.js provided by Bootstrap framework.
See http://formvalidation.io/getting-started/#including-library

Also, I suggested you move formValidation.js (and other plugins) to separated, its own directory.

Here is what you need to change:

BEFORE:
```html
<script type="text/javascript" src="${pageContext.request.contextPath}/resources/js/bootstrap.js"></script> 
<script type="text/javascript" src="${pageContext.request.contextPath}/resources/js/formValidation.js"></script> 
```

AFTER:
```html
<!-- This is Bootstrap JS from Bootstrap framework -->
<script type="text/javascript" src="${pageContext.request.contextPath}/resources/js/bootstrap.js"></script> 

<!-- FormValidation JS -->
<script type="text/javascript" src="${pageContext.request.contextPath}/resources/js/formvalidation/dist/js/formValidation.js"></script> 

<!-- To use FormValidation with Bootstrap form, we need to include this -->
<script type="text/javascript" src="${pageContext.request.contextPath}/resources/js/formvalidation/dist/js/framework/bootstrap.js"></script>
```

**Comment by bhames50** [comment]
Are you saying I need both bootstrap.js files, one from them and one from you? And, I need to put them in separate directories so they won't conflict with each other? And, the one from you needs to be in the same directory as your .js file? 
I will have to say that if this is the case, you need to make a bigger point of it on your website as it is not obvious, and only after having you explain it do I understand.
I will try the changes you suggest tomorrow, and let you know if I get them working.

**Comment by nghuuphuoc** [comment]
> Are you saying I need both bootstrap.js files, one from them and one from you

Exactly. They have the same name but diffrent content.
I will update the documentation to avoid the confusion for other one.

**Comment by nghuuphuoc** [comment]
I updated both [Upgrading to v0.6.0](http://formvalidation.io/news/upgrading-to-v0.6.0/) and [Including library](http://formvalidation.io/getting-started/#including-library) sections!
Hopefully it can help other users not be confused.

**Comment by bhames50** [comment]
I tried loading the bootstrap.js file you supplied, and I put everything in the directory structure you specified. It is working now, and I checked the changes to the website, and they are much better.

Thanks!

**Comment by nghuuphuoc** [comment]
You're welcome. Feel free to ask me any questions/issues in the future :)
