### ISSUE TITLE
Form Validation of dynamic fields

### ISSUE THREAD

**Issue by gunjanvarshney** [formvalidation/formvalidation.io#8]
Hello,

First of all this is a fantastic plugin to do form validation out there. great work!!!

I have an issue for which I need help in v 0.5.3. I have a dynamic form where on click of add button I am cloning a row. the row is cloned using HTML template as there are some third party plugins (selectize) being used. what is happening is that for newly added fields (with same id/selector) I am not able to include them (new fields in new row) for form validation - the astrix doesnt show.

I am adding fields using addField with string (id of the fields) as paramter.

the initial options for initialization includes fields with selector on it. 

I am using your example code to put in astrix for mandatory fields as below. 

	     jMainForm
		.on('init.field.bv', function(e, data) {
	        // data.bv      --> The BootstrapValidator instance
	        // data.field   --> The field name
	        // data.element --> The field element
	
	        var $parent    = data.element.parents('.form-group'),
	            $icon      = $parent.find('.form-control-feedback[data-bv-icon-for="' + data.field + '"]'),
	            options    = data.bv.getOptions(),                      // Entire options
	            validators = data.bv.getOptions(data.field).validators; // The field validators
	
	        if (validators.notEmpty && validators.notEmpty.enabled && options.feedbackIcons && options.feedbackIcons.required) {
	            // The field uses notEmpty validator
	            // Add required icon
	            $icon.addClass(options.feedbackIcons.required).show();
	        }
	        	        
	        data.bv.disableSubmitButtons(false);
	    })

**Comment by vaibhav-jain** [comment]
I want to validate dynamic form. Can you tell me how you validate newly added fields.??? How do i add validator for newly added fields????

**Comment by nghuuphuoc** [comment]
You can use the [addField()](http://formvalidation.io/api/#add-field) method

```javascript
$(form).formValidation('addField', $fullname, {
    validators: { 
        notEmpty: {
            message: 'Name is required'
        },
        stringLength: {
            min: 2,
            max: 25,
            message: '2 to 25 characters please'
        }
    }
});
```

PS: Next time, please submit the issues on the [main repos](https://github.com/formvalidation/formvalidation/issues)

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by nghuuphuoc** [comment]
This issue was moved to formvalidation/support#3
